name: Test Automation Framework Workflow

on:
  schedule:
    - cron: '00 18 * * *'
    - cron: '15 04 * * *'
    - cron: '15 16 * * *'
    - cron: '30 01 * * 1-5'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Running Test Automation Framework with Maven
      run: mvn test -Dbrowser=chrome -DisLamdaTest=true -DisHeadless=false -X



    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v7.0.1
      with: 
        name: Test Logs
        path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v7.0.1
      with: 
        name: screenshots
        path: screenshots/
        
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v7.0.1
      with: 
        name: Test Reports
        path: report.html

    - name: Copy Reports to gh-Pages Folder
      if: always()
      run: |
        mkdir -p public/extent-reports
        cp report.html public/extent-reports/index.html
        cp -R screenshots/ public/extent-reports/screenshots/

    - name: Deploy to GitHub Pages
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        folder: public/extent-reports/
        token: ${{ github.TOKEN }}
        clean: true
         
    - name: Send Email
      if: always()
      uses: dawidd6/action-send-mail@v16
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: UI Automation Framework Report
        to: shlokprakash55@gmail.com
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
             Hi,
             Ui Automation Framework tests has been executed. The Report has been published and the URL 
             is: https://shlok-prakash.github.io/Test-Automation-Framework/
        # attachments: public/extent-reports/index.html
